// Regenerates src/glyphs.js from @phosphor-icons/core (bold weight).
// Run with: node scripts/build-glyphs.mjs
import { readFileSync, writeFileSync } from 'node:fs';

const dir = new URL('../node_modules/@phosphor-icons/core/assets/bold/', import.meta.url);

const UI = {
  undo: 'arrow-u-up-left', redo: 'arrow-u-up-right', more: 'dots-three', download: 'download-simple',
  copy: 'copy', link: 'link-simple', paste: 'clipboard-text', close: 'x', check: 'check', warning: 'warning',
  plus: 'plus', minus: 'minus', fit: 'corners-out', shuffle: 'shuffle', save: 'bookmark-simple',
  trash: 'trash', upload: 'upload-simple', alignLeft: 'text-align-left', alignCenter: 'text-align-center',
  alignRight: 'text-align-right', swap: 'arrows-left-right', keyboard: 'keyboard', github: 'github-logo',
  caret: 'caret-down', info: 'info', share: 'share-network', globe: 'globe-simple', reset: 'arrow-counter-clockwise',
};

// Centre-logo icons. Keys are stored in saved designs — keep them stable.
const LOGO = {
  link: 'link-simple', globe: 'globe', menu: 'fork-knife', bag: 'shopping-bag', calendar: 'calendar-blank',
  pin: 'map-pin', mail: 'envelope-simple', phone: 'phone', wifi: 'wifi-high', play: 'play', music: 'music-note',
  camera: 'camera', coffee: 'coffee', heart: 'heart', star: 'star', user: 'user', sparkles: 'sparkle',
  instagram: 'instagram-logo', whatsapp: 'whatsapp-logo', tiktok: 'tiktok-logo', youtube: 'youtube-logo',
  facebook: 'facebook-logo', linkedin: 'linkedin-logo', spotify: 'spotify-logo',
};

const inner = (name) =>
  readFileSync(new URL(`${name}-bold.svg`, dir), 'utf8').replace(/^<svg[^>]*>/, '').replace(/<\/svg>\s*$/, '');

const dump = (map) =>
  Object.entries(map).map(([k, n]) => `  ${k}: ${JSON.stringify(inner(n))},`).join('\n');

writeFileSync(
  new URL('../src/glyphs.js', import.meta.url),
  `// Generated by scripts/build-glyphs.mjs from Phosphor Icons (MIT, https://phosphoricons.com).
// All glyphs use a 0 0 256 256 viewBox and are filled with currentColor.

export const UI_GLYPHS = {\n${dump(UI)}\n};

export const LOGO_GLYPHS = {\n${dump(LOGO)}\n};
`,
);
console.log('src/glyphs.js written');
